[package]
name = "kripke-game-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["env", "derive"] }
combine = "4.6.7"
itertools = "0.14.0"
rand = "0.9.2"
rayon = "1.11.0"
